### ISSUE TITLE
Failed to Read Tensor Data on Quantized Model

### ISSUE THREAD

**Issue by ecyht2** [mmwillet/TTS.cpp#6] opened 2024-12-26 05:28 UTC
I tried out the new version and it seems like there is an error when trying to load a quantized model.

> gguf_init_from_file: failed to read tensor data
TTS.cpp/src/parler.cpp:604: runner_from_file failed for file models/parler-tts-mini-v1-Q5_0.gguf

**Comment by mmwillet** [comment] 2024-12-26 06:19
Recreated. Taking a look now.

**Comment by mmwillet** [comment] 2024-12-26 07:30
Should be fixed with https://github.com/mmwillet/TTS.cpp/commit/d09ec72e22af529f20d0c47ae4ce7220f14aeda1

I tested cpu generation with and without cross attention and it seems fine now.

The cause was just that there was meta for the top level model tensor (which was removed) added to the gguf file.

**Closed by mmwillet** 2024-12-26 07:30 UTC
